package.json

Missing and causing release failure.

Adding AI PAckage

---

src/app/contact/views/faqs.ejs

NSA-1636 update FAQ's

---

src/app/contact/views/faqs.ejs

NSA-1636 Update FAQs

---

package-lock.json
package.json
src/app/contact/getContactForm.js
src/app/contact/postContactForm.js
src/app/contact/views/contactForm.ejs
test/appTests/contactTests/postContactForm.test.js

Changed service field to dropdown selection and added type of issue field

Nsa 1667 contact form update

---

package-lock.json
package.json
src/app/contact/postContactForm.js
test/appTests/contactTests/postContactForm.test.js

Send confirmation of help form to user

Nsa 1723 help form confirmation email

---

src/app/contact/getConfirm.js
src/app/contact/getContactForm.js
src/app/contact/getFaqs.js
src/app/layouts/layout.ejs
src/dist/robots.txt
src/index.js

Prevent indexing of contact form

Nsa 1772 help form indexing

---

package-lock.json
package.json

updated error handling version

NSA-1808-IE-compatibility

---

azure/parameters.json
azure/template.json

Updated templates

---

src/app/contact/views/faqs.ejs

FAQ content update for when approver functionality is switched on

NSA-1913 FAQ content update

---

src/app/contact/getCreateAccountHelp.js
src/app/contact/help.js
src/app/contact/index.js
src/app/contact/views/contactForm.ejs
src/app/contact/views/createAccountHelp.ejs
src/app/contact/views/help.ejs

Add radio button for setting up DSI account

NSA-2144- create account radio

---

src/app/contact/getConfirm.js
src/app/contact/views/confirm.ejs

NSA-2308 - confirmation content

---

src/app/contact/postContactForm.js

Service now sends an auto email so this is no longer required

NSA-2309 - remove confirmation email

---

src/app/contact/views/accessService.ejs
src/app/contact/views/approverHelp.ejs
src/app/contact/views/createAccountHelp.ejs

NSA-2367 DfE Sign-in Help - Self Reg Change

NSA-2367 DfE Sign-in Help - Self Reg Change

---

src/app/contact/selectService.js
src/app/contact/views/contactForm.ejs

NSA-2286-cr

---

azure/parameters.json
azure/template.json

Updated azure template

---

src/app/requests/views/howToApprove.ejs
src/app/requests/views/howToReject.ejs
src/app/requests/views/requests.ejs

Jira ticket https://dfe-secureaccess.atlassian.net/browse/NSA-5579
Updated the content for:
-  the first step and the updated date  for the 'How to approve an organisation request' article
-  the first step and the updated date  for the 'How to reject an organisation request' article

Content Updates to Help articles for the Requests changes

---

src/app/shared/views/layout.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-5447

NSA-5447_Added "Accessibility statement" link in the footer

---

src/app/contactUs/postContactUs.js
src/app/shared/views/layout.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-5630

feature/NSA-5630_updated_page_title_to_include_error_message_info 

---

Docker/init.sh
Dockerfile
README.md
docker-compose.debug.yml
docker-compose.yml
package.json

added compose fixed docker run command error

added compose

---

src/app/menus/views/manageConMenu.ejs

**Jira ticket:** 
https://dfe-secureaccess.atlassian.net/browse/NSA-7463
**Changes:**
Added Help link to the Navigation Ribbon for Manage Console menu

[NSA-7463] - Add help section to manage console ribbon

---

src/app/manageUsers/views/changeSubServiceToUser.ejs

Jira ticket:(https://dfe-secureaccess.atlassian.net/browse/NSA-7319)
Changes: 
`How to change sub-service access on an end user’s account help page` corrections

[NSA-7319] Help page correction how to change sub service access

---

src/app/requests/views/howToReject.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-7317
Changes: How do I reject a request? - help page corrections

NSA-7317 - correct how to reject request help page

---

src/app/services/views/requestAccess.ejs

https://dfe-secureaccess.atlassian.net/browse/NSA-7325

added work as per ticket

---

src/app/requests/views/howToApprove.ejs

Changes:
- corrections to `How do I approve a request help` page

[NSA-7316] - corrections to how do I approve a request help page

---

src/app/manageConsole/views/howtoEditServiceConfig.ejs

Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-7464
Changes: 
- updated the identifier for the 'Service details' element to facilitate linking between the Service configuration changes page and the relevant section on the Help page.

[NSA-7464] Updated service details heading id

---

src/app/services/views/requestAccess.ejs

commit fix to review

---

package.json
src/app/manageConsole/howtoEditServiceConfig.js
src/app/manageUsers/manageUsers.js
src/app/organisations/organisations.js
src/app/profile/profile.js
src/app/services/services.js
src/app/shared/views/layout.ejs
test/app/manageConsole/howtoEditServiceConfig.get.test.js
test/app/manageConsole/manageDashboard.get.test.js
test/app/profile/profile.get.test.js
test/utils/index.js

https://dfe-secureaccess.atlassian.net/browse/DSI-6517
make links open in new tab

completed work

---

src/app/requests/requests.js

https://dfe-secureaccess.atlassian.net/browse/DSI-6517
added a return link to allow new tabs to be directed to main help page

added fix to link

---

DevOps/pipeline/azure-pipeline.yml

Keyvault firewall Enable (#221)

---

package-lock.json
package.json
src/index.js

Jira ticket
https://dfe-secureaccess.atlassian.net.mcas.ms/jira/software/c/projects/DSI/boards/14?selectedIssue=DSI-6938
Content security policy has been refactored to exclude localhsot for live environments
- Add the Header X-Contact-Type-Options
- Set the Strict-Transport-Security where headers missing
- Remove CSP headers extra information
- Set X-Frame-Options
- Set X-XSS-Protection
- Set X-Content-Type-Options
- Remove fingerprints of server e.g. powered by express
Progress https://dfe-secureaccess.atlassian.net.mcas.ms/wiki/spaces/NSA/pages/3947528194/ITHC+April+2024+-+Medium+Priority+Recommendations

DSI-7011 ITHC changes 

---

src/app/menus/views/serviceMenu.ejs

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7050
-    Change the navigation title from 'Services' to 'My services'

[DSI-7050]-Change the navigation title from 'Services' to 'My services'

---

package-lock.json
src/app/menus/views/serviceMenu.ejs

Jira ticket: https://dfe-secureaccess.atlassian.net/browse/DSI-7133
- Navigation title reverted to “Services” as the navigation menu was too wide and displaced to the next line.
- Fix 1 vulnerable package using `npm audit fix` command
https://github.com/DFE-Digital/login.dfe.help/pull/235

[DSI-7133] Navigation menu displaced to the next line

---

package-lock.json
package.json
src/index.js

**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7157
- Remove unnecessary `morgan` middleware and HTTP request logging to `access.log`

[DSI-7157] Remove unnecessary `morgan` middleware 

---

src/app/dashboard/managDashboard.js
src/app/dashboard/views/manageDashboard.ejs
src/app/shared/views/layout.ejs
test/app/manageConsole/manageDashboard.get.test.js

Jira ticket: [DSI-6534](https://dfe-secureaccess.atlassian.net/browse/DSI-6534)
- Updated content of the Manage Console Help
- Updated test.

[DSI-6534] Step 0 manage console help

---

src/app/endUsers/views/endUsers.ejs
src/app/organisations/addMultipleOrganisations.js
src/app/organisations/views/addMultipleOrganisations.ejs
src/app/organisations/views/organisations.ejs
src/app/profile/views/profile.ejs
src/app/profile/views/setupAccount.ejs
src/app/shared/views/layout.ejs

Jira ticket: [DSI-6667](https://dfe-secureaccess.atlassian.net/browse/DSI-6667)
- Updated content of 'adding multiple organisation' and 'set up account' help page 
- Fixed moderate issue in heading levels with axeDevTools

[DSI-6667] Update to DSI help finding organisations

---

package-lock.json
src/app/dashboard/index.js
src/app/dashboard/views/manageDashboard.ejs
src/app/manageConsole/aboutManageConsole.js
src/app/manageConsole/index.js
src/app/manageConsole/views/aboutManageConsole.ejs
src/app/manageConsole/views/howtoEditServiceConfig.ejs
test/app/manageConsole/aboutManageConsole.get.test.js

Jira: [DSI-6538](https://dfe-secureaccess.atlassian.net/browse/DSI-6538?atlOrigin=eyJpIjoiMTJhMGMwNmM0MjljNDUxYWE0NTlhMzg2NjZkNTEwNDYiLCJwIjoiaiJ9)
- Add route and help page for `about-manage-console`
- Updated date on the Manage Dashboard to match new page date.
- Created new test case for page
- Fix minor NPM vulnerabilities with `npm audit fix`

[DSI-6538] Add help page for `manage console`

---

src/app/dashboard/views/manageDashboard.ejs
src/app/manageConsole/howtoViewAndSearchOrganisations.js
src/app/manageConsole/index.js
src/app/manageConsole/views/howtoViewAndSearchOrganisations.ejs
test/app/manageConsole/howtoViewAndSearchOrganisations.get.test.js

Jira ticket: [DSI-6537](https://dfe-secureaccess.atlassian.net/browse/DSI-6537)
- Created "How to view and search organisations" page.
- Create a new route to support the new page.
- Updated date on the Manage Dashboard to match new page date.
- Created test to support "How to view and search organisations" page.

[DSI-6537] Step 2 manage console view and search organisations

---

src/app/manageConsole/views/howtoEditServiceConfig.ejs

Jira ticket: [DSI-6554](https://dfe-secureaccess.atlassian.net/browse/DSI-6554)
- Update text content in how to edit service config page

[DSI-6554] Update Client ID help text following the change from Read Only 

---

package-lock.json
src/app/contactUs/postContactUs.js
src/app/contactUs/referrerValidator.js
test/app/contactUs/contactUs.post.test.js
test/app/contactUs/referrerValidator.test.js

Jira: https://dfe-secureaccess.atlassian.net/browse/DSI-7406
- Implemented `isValidReferrer` for validating the referrer
- Add significant test coverage for `isValidReferrer`
- Updated postContactUs to utilise `isValidReferrer`
- Updated postContactUs unit tests

[DSI-7406] Fix XSS vulnerability

---

src/app/dashboard/views/manageDashboard.ejs
src/app/manageConsole/views/howtoEditServiceConfig.ejs

Jira ticket: [DSI-6555](https://dfe-secureaccess.atlassian.net/browse/DSI-6555)
- Update service configuration help text following the change in URL validations and DfE Sign-in manage console name change.
- Replace tag ordered list for unordered list when is a bullet list.

[DSI-6555] Update service configuration help text
